openapi: 3.0.0
info:
  title: Horoscope Service API
  version: 1.0.0
  description: Returns daily and historical horoscopes

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /horoscope/today:
    get:
      summary: Get today's horoscope
      responses:
        '200':
          description: Horoscope returned
        '401':
          description: Unauthorized
        '404':
          description: Not found
  /horoscope/history:
    get:
      summary: Get past 7 days of horoscope
      responses:
        '200':
          description: History returned
        '401':
          description: Unauthorized
        '404':
          description: Not found
